defmodule Alembic.Supervisors.MobSupervisor do
  @moduledoc """
  A DynamicSupervisor for managing Mob GenServer processes.

  Each mob (monster/enemy) runs as a separate Mob GenServer under this supervisor.
  Mobs are spawned by Zones and managed here for fault tolerance.

  ## Lifecycle
  - Zone spawn point triggers → `spawn_mob/2` creates a Mob GenServer
  - Mob dies → `despawn_mob/1` terminates the process
  - Mob respawns → Zone calls `spawn_mob/2` again after respawn timer
  - Mob crashes → Supervisor restarts (but Zone may need to re-register position)

  ## Spawn Management
  Zones are responsible for:
  - Deciding when to spawn mobs (based on spawn points, timers)
  - Tracking mob positions
  - Handling mob respawns

  MobSupervisor just manages the process lifecycle.
  """

  use DynamicSupervisor

  alias Alembic.Entity.Mob

  def start_link(init_arg) do
    DynamicSupervisor.start_link(__MODULE__, init_arg, name: __MODULE__)
  end

  @impl true
  def init(_init_arg) do
    DynamicSupervisor.init(strategy: :one_for_one)
  end

  @doc """
  Spawns a new mob under this supervisor.

  ## Options
  - `:id` - Unique mob ID (required, typically generated by Zone)
  - `:name` - Mob display name (e.g., "Goblin Warrior")
  - `:type` - Mob type atom (e.g., :goblin, :dragon)
  - `:position` - Starting position in zone
  - `:stats` - Mob stats (HP, attack, etc.)
  - `:ai_state` - Initial AI state (defaults to :idle)
  - `:aggro_range` - How far the mob can detect players
  - `:loot_table` - Items/gold dropped on death

  ## Examples

      iex> MobSupervisor.spawn_mob("mob_goblin_001",
      ...>   name: "Goblin Scout",
      ...>   type: :goblin,
      ...>   position: position
      ...> )
      {:ok, #PID<0.456.0>}
  """
  def spawn_mob(mob_id, opts \\ []) do
    mob_opts = Keyword.put(opts, :id, mob_id)
    child_spec = {Mob, mob_opts}

    case DynamicSupervisor.start_child(__MODULE__, child_spec) do
      {:ok, pid} -> {:ok, pid}
      {:error, {:already_started, pid}} -> {:ok, pid}
      {:error, reason} -> {:error, reason}
    end
  end

  @doc """
  Despawns (removes) a mob.
  Called when a mob dies or when a zone is unloaded.

  ## Examples

      iex> MobSupervisor.despawn_mob("mob_goblin_001")
      :ok
  """
  def despawn_mob(mob_id) do
    case Registry.lookup(Alembic.Registry.MobRegistry, mob_id) do
      [{pid, _}] ->
        DynamicSupervisor.terminate_child(__MODULE__, pid)
      [] ->
        {:error, :not_found}
    end
  end

  @doc """
  Returns a list of all mob PIDs currently running.
  """
  def list_mobs do
    DynamicSupervisor.which_children(__MODULE__)
    |> Enum.map(fn {_id, pid, _type, _modules} -> pid end)
    |> Enum.filter(&is_pid/1)
  end

  @doc """
  Returns the count of active mobs across all zones.
  """
  def count_mobs do
    case DynamicSupervisor.count_children(__MODULE__) do
      %{active: count} -> count
      _ -> 0
    end
  end

  @doc """
  Returns true if a mob is currently spawned.
  """
  def mob_spawned?(mob_id) do
    case Registry.lookup(Alembic.Registry.MobRegistry, mob_id) do
      [{_pid, _}] -> true
      [] -> false
    end
  end

  @doc """
  Returns statistics about the mob supervisor.
  """
  def stats do
    children = DynamicSupervisor.count_children(__MODULE__)

    %{
      active: children.active,
      supervisors: children.supervisors,
      workers: children.workers
    }
  end

  @doc """
  Despawns all mobs in a given zone.
  Used when unloading a zone.

  ## Examples

      iex> MobSupervisor.despawn_all_in_zone("zone_overworld")
      :ok
  """
  def despawn_all_in_zone(zone_id) do
    # TODO: This requires tracking zone_id -> mob_ids mapping
    # For now, zones should track their own mobs and call despawn_mob individually
    :ok
  end
end
